"""Update CollectionOrder with detailed address and relationships

Revision ID: 052ec67bb412
Revises: 0bda50924a47
Create Date: 2026-03-24 20:04:00.915638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052ec67bb412'
down_revision: Union[str, Sequence[str], None] = '0bda50924a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_orders', sa.Column('street', sa.String(length=255), nullable=False))
    op.add_column('collection_orders', sa.Column('number', sa.String(length=50), nullable=False))
    op.add_column('collection_orders', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('collection_orders', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('collection_orders', sa.Column('zip_code', sa.String(length=20), nullable=False))
    op.add_column('collection_orders', sa.Column('distribution_center_id', sa.UUID(), nullable=True))
    op.add_column('collection_orders', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'collection_orders', 'distribution_centers', ['distribution_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'collection_orders', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_orders', type_='foreignkey')
    op.drop_constraint(None, 'collection_orders', type_='foreignkey')
    op.drop_column('collection_orders', 'vehicle_id')
    op.drop_column('collection_orders', 'distribution_center_id')
    op.drop_column('collection_orders', 'zip_code')
    op.drop_column('collection_orders', 'state')
    op.drop_column('collection_orders', 'city')
    op.drop_column('collection_orders', 'number')
    op.drop_column('collection_orders', 'street')
    # ### end Alembic commands ###
