"""Add tenant_settings table

Revision ID: 11fcbff40249
Revises: ecf7bacbe0fb
Create Date: 2026-03-22 11:28:44.592029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fcbff40249'
down_revision: Union[str, Sequence[str], None] = 'ecf7bacbe0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('ai_tone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    
    # Passos para adicionar coluna Not Null com valor default em tabelas existentes
    op.add_column('distribution_centers', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE distribution_centers SET version = 1')
    op.alter_column('distribution_centers', 'version', nullable=False)
    
    op.add_column('inventory_transactions', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE inventory_transactions SET version = 1')
    op.alter_column('inventory_transactions', 'version', nullable=False)
    
    op.add_column('products', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE products SET version = 1')
    op.alter_column('products', 'version', nullable=False)
    
    op.add_column('sales_orders', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE sales_orders SET version = 1')
    op.alter_column('sales_orders', 'version', nullable=False)
    
    op.add_column('vehicles', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE vehicles SET version = 1')
    op.alter_column('vehicles', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'version')
    op.drop_column('sales_orders', 'version')
    op.drop_column('products', 'version')
    op.drop_column('inventory_transactions', 'version')
    op.drop_column('distribution_centers', 'version')
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
