"""Add Help and ChatbotLog models

Revision ID: 148e7938f8e5
Revises: 712edc1f599c
Create Date: 2026-03-19 16:48:36.791407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148e7938f8e5'
down_revision: Union[str, Sequence[str], None] = '712edc1f599c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_articles_category'), 'help_articles', ['category'], unique=False)
    op.create_table('chatbot_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_logs_tenant_id'), 'chatbot_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chatbot_logs_user_id'), 'chatbot_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_logs_user_id'), table_name='chatbot_logs')
    op.drop_index(op.f('ix_chatbot_logs_tenant_id'), table_name='chatbot_logs')
    op.drop_table('chatbot_logs')
    op.drop_index(op.f('ix_help_articles_category'), table_name='help_articles')
    op.drop_table('help_articles')
    # ### end Alembic commands ###
