"""Add Vehicle table for TMS

Revision ID: 16ae95968b28
Revises: d31292a1d49a
Create Date: 2026-03-19 13:58:59.803369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ae95968b28'
down_revision: Union[str, Sequence[str], None] = 'd31292a1d49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('tare_weight', sa.Float(), nullable=False),
    sa.Column('max_weight_capacity', sa.Float(), nullable=False),
    sa.Column('max_volume_capacity', sa.Float(), nullable=False),
    sa.Column('compartment_width', sa.Float(), nullable=False),
    sa.Column('compartment_height', sa.Float(), nullable=False),
    sa.Column('compartment_length', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'license_plate', name='uq_tenant_license_plate')
    )
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
