"""add_product_logistics_fields_and_constraints

Revision ID: 1a59ac344147
Revises: 5a7919f0a5b7
Create Date: 2026-03-19 09:30:11.152704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a59ac344147'
down_revision: Union[str, Sequence[str], None] = '5a7919f0a5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('length', sa.Float(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_unique_constraint('uq_tenant_barcode', 'products', ['tenant_id', 'barcode'])
    op.create_unique_constraint('uq_tenant_sku', 'products', ['tenant_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_sku', 'products', type_='unique')
    op.drop_constraint('uq_tenant_barcode', 'products', type_='unique')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('products', 'length')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
