"""add_current_stock

Revision ID: 242732ae6a72
Revises: fa8b0b27f695
Create Date: 2026-03-17 15:32:25.041628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242732ae6a72'
down_revision: Union[str, Sequence[str], None] = 'fa8b0b27f695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('current_stock', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ######


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_stock')
    # ### end Alembic commands ###
