"""add_cost_price

Revision ID: 3b952e98334c
Revises: ce099b5a017a
Create Date: 2026-03-18 10:54:31.196638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b952e98334c'
down_revision: Union[str, Sequence[str], None] = 'ce099b5a017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
