"""Add embedding to HelpArticle

Revision ID: 4d0ce9def7f4
Revises: 148e7938f8e5
Create Date: 2026-03-20 10:31:21.822893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4d0ce9def7f4'
down_revision: Union[str, Sequence[str], None] = '148e7938f8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_articles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('help_articles', 'embedding')
    # ### end Alembic commands ###
