"""add_unit_price_cost_to_transactions

Revision ID: 657baa72048e
Revises: 3b952e98334c
Create Date: 2026-03-18 12:30:57.301808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657baa72048e'
down_revision: Union[str, Sequence[str], None] = '3b952e98334c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('inventory_transactions', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_transactions', 'unit_cost')
    op.drop_column('inventory_transactions', 'unit_price')
    # ### end Alembic commands ###
