"""add_hashed_password

Revision ID: 703192733287
Revises: 
Create Date: 2026-03-17 09:44:11.570179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '703192733287'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('inventory_transactions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory_transactions', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory_transactions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_tenant_id'), 'inventory_transactions', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('inventory_transactions_user_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'created_at')
    op.drop_column('inventory_transactions', 'user_id')
    op.drop_column('inventory_transactions', 'reason')
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('products', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('products_tenant_id_sku_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'category')
    op.drop_column('products', 'unit_price')
    op.drop_column('products', 'barcode')
    op.alter_column('tenants', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tenants_subdomain_key'), 'tenants', type_='unique')
    op.drop_column('tenants', 'subdomain')
    op.drop_column('tenants', 'primary_color')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'secondary_color')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'hashed_password')
    op.add_column('tenants', sa.Column('secondary_color', sa.TEXT(), server_default=sa.text("'#FFFFFF'::text"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('primary_color', sa.TEXT(), server_default=sa.text("'#000000'::text"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('subdomain', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tenants_subdomain_key'), 'tenants', ['subdomain'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('products', sa.Column('barcode', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('min_stock_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_unique_constraint(op.f('products_tenant_id_sku_key'), 'products', ['tenant_id', 'sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('products', 'price')
    op.add_column('inventory_transactions', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transactions_user_id_fkey'), 'inventory_transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_inventory_transactions_tenant_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_transactions', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inventory_transactions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('inventory_transactions', 'date')
    # ### end Alembic commands ###
