"""Add cd_id to products

Revision ID: 708fda2a7ba2
Revises: 11fcbff40249
Create Date: 2026-03-22 11:57:49.324762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708fda2a7ba2'
down_revision: Union[str, Sequence[str], None] = '11fcbff40249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cd_id', sa.UUID(), nullable=True))
    op.alter_column('products', 'ncm',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('products', 'origin',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.create_foreign_key(None, 'products', 'distribution_centers', ['cd_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'origin',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('products', 'ncm',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.drop_column('products', 'cd_id')
    # ### end Alembic commands ###
