"""add_contact_name_to_suppliers

Revision ID: 9333ae421105
Revises: b69d9a04956c
Create Date: 2026-03-23 03:50:45.166831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9333ae421105'
down_revision: Union[str, Sequence[str], None] = 'b69d9a04956c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contact_name')
    # ### end Alembic commands ###
