"""Add cd_id to purchase_orders for inbound operations

Revision ID: b69d9a04956c
Revises: 708fda2a7ba2
Create Date: 2026-03-22 12:34:30.248863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69d9a04956c'
down_revision: Union[str, Sequence[str], None] = '708fda2a7ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('cd_id', sa.UUID(), nullable=True))
    op.add_column('purchase_orders', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE purchase_orders SET version = 1')
    op.alter_column('purchase_orders', 'version', nullable=False)
    op.create_foreign_key(None, 'purchase_orders', 'distribution_centers', ['cd_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'version')
    op.drop_column('purchase_orders', 'cd_id')
    # ### end Alembic commands ###
