"""Add fiscal fields

Revision ID: eb247c315d44
Revises: 1a59ac344147
Create Date: 2026-03-19 10:13:34.485638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb247c315d44'
down_revision: Union[str, Sequence[str], None] = '1a59ac344147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ncm', sa.String(length=8), nullable=True))
    op.add_column('products', sa.Column('cfop', sa.String(length=4), nullable=True))
    op.add_column('products', sa.Column('cest', sa.String(length=7), nullable=True))
    op.add_column('products', sa.Column('origin', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('cnpj', sa.String(length=14), nullable=True))
    op.add_column('tenants', sa.Column('corporate_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('tax_regime', sa.String(length=50), nullable=True))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_tenants_cnpj'), 'tenants', ['cnpj'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_cnpj'), table_name='tenants')
    op.alter_column('tenants', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tenants', 'tax_regime')
    op.drop_column('tenants', 'corporate_name')
    op.drop_column('tenants', 'cnpj')
    op.drop_column('products', 'origin')
    op.drop_column('products', 'cest')
    op.drop_column('products', 'cfop')
    op.drop_column('products', 'ncm')
    # ### end Alembic commands ###
