"""Add distribution_centers and vehicle cd_id

Revision ID: ecf7bacbe0fb
Revises: 4d0ce9def7f4
Create Date: 2026-03-22 08:59:13.437534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf7bacbe0fb'
down_revision: Union[str, Sequence[str], None] = '4d0ce9def7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_centers_tenant_id'), 'distribution_centers', ['tenant_id'], unique=False)
    op.add_column('vehicles', sa.Column('cd_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'distribution_centers', ['cd_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'cd_id')
    op.drop_index(op.f('ix_distribution_centers_tenant_id'), table_name='distribution_centers')
    op.drop_table('distribution_centers')
    # ### end Alembic commands ###
